services:
  postgres:
    image: postgres:latest
    container_name: postgres-medical-history

    environment:
       POSTGRES_USER: Gianlu00
       POSTGRES_PASSWORD: brezen
       POSTGRES_DB: medical-db
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql
volumes:
  postgres-data: