services:
  postgres:
    image: postgres:latest
    container_name: postgres-medical-history
    environment:
       POSTGRES_USER: Gianlu00
       POSTGRES_PASSWORD: brezen
       POSTGRES_DB: medical-db
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql

  minio:
    image: minio/minio
    container_name: minio-medical-history
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data

volumes:
  postgres-data:
  minio-data: